{{cookiecutter.license}}

TARGET=cov

include Makefile.inc
INCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include

{% if cookiecutter.datasources == "True" %}
LIBRARIES   += ../../Source/Components/DataSources/$(TARGET)/DataSources$(LIBEXT)
{% endif %}
{%- if cookiecutter.gams == "True" -%}
LIBRARIES   += ../../Source/Components/GAMs/$(TARGET)/GAMs$(LIBEXT)
{% endif %}
{%- if cookiecutter.interfaces == "True" -%}
LIBRARIES   += ../../Source/Components/Interfaces/$(TARGET)/Interfaces$(LIBEXT)
{% endif %}
{%- if cookiecutter.interfaces == "True" -%}
LIBRARIES   += ../../Test/Components/Interfaces/$(TARGET)/InterfacesTests$(LIBEXT)
{% endif %}
{%- if cookiecutter.datasources == "True" -%}
LIBRARIES   += ../../Test/Components/DataSources/$(TARGET)/DataSourcesTests$(LIBEXT)
{% endif %}
{%- if cookiecutter.gams == "True" -%}
LIBRARIES   += ../../Test/Components/GAMs/$(TARGET)/GAMsTests$(LIBEXT)
{% endif %}
LIBRARIES   += -L$(MARTe2_DIR)/Build/x86-linux/Core/ -lMARTe2
LIBRARIES   += $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest.a 

ifdef CODAC_ROOT
LIBRARIES += -L$(CODAC_ROOT)/lib/
LIBRARIES += -lnisync
LIBRARIES += -lnixseries
LIBRARIES += -lpxi6259
LIBRARIES += -lNiFpga

## Only force EPICSPVA if CCS version is gt v6.1
CCSGT61 = $(shell if [ `codac-version -v | sed 's/\(.*\)\.\(.*\)/\1\2/g'` -ge 61 ]; then echo 1; else echo 0; fi)
ifeq "$(CCSGT61)" "1"
EPICSPVA = "1"
endif

endif

ifdef EFDA_MARTe_DIR
LIBRARIES   += -L$(EFDA_MARTe_DIR)/Interfaces/BaseLib2Adapter/linux -lBaseLib2Adapter -L$(EFDA_MARTe_DIR)/BaseLib2/linux -lBaseLib2
endif

ifdef MDSPLUS_DIR
LIBRARIES += -L$(MDSPLUS_DIR)/lib64 -lMdsObjectsCppShr
endif

ifdef EPICS_BASE
LIBRARIES += -L$(EPICS_BASE)/lib/$(EPICS_HOST_ARCH)/ -lca
endif

ifdef EPICSPVA
LIBRARIES += -lpvaClient -lpvAccess -lpvData -lpvDatabase
endif 
